# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-zRkbyvomlo7imfSDU52wN-uuFh376o
"""

!pip install textblob streamlit

# app.py
import pandas as pd
from textblob import TextBlob
import streamlit as st

# Load the dataset
@st.cache_data
def load_data():
    df = pd.read_excel("/content/FInal.xlsx", sheet_name="Form Responses 1")
    df.columns = [
        "Likes_Dislikes",
        "Overall_Experience",
        "Recommend",
        "Email"
    ]
    df = df.drop(columns=["Email"])
    df.dropna(how="all", inplace=True)
    df.dropna(subset=["Likes_Dislikes", "Overall_Experience"], how="all", inplace=True)
    df.fillna("", inplace=True)
    df["Combined_Text"] = df["Likes_Dislikes"] + " " + df["Overall_Experience"]
    return df

# Perform sentiment analysis
def analyze_sentiment(text):
    analysis = TextBlob(text)
    polarity = analysis.sentiment.polarity
    if polarity > 0.05:
        return "Positive"
    elif polarity < -0.05:
        return "Negative"
    else:
        return "Neutral"

# Streamlit App
def main():
    st.title("🎬 Jai Ho Sentiment Analysis App")

    df = load_data()

    st.subheader("Raw Combined Feedback")
    st.dataframe(df[["Combined_Text", "Recommend"]])

    df["Sentiment"] = df["Combined_Text"].apply(analyze_sentiment)

    st.subheader("Sentiment Analysis Result")
    st.dataframe(df[["Combined_Text", "Sentiment", "Recommend"]])

    sentiment_counts = df["Sentiment"].value_counts()
    st.subheader("Sentiment Distribution")
    st.bar_chart(sentiment_counts)

    st.subheader("Recommendation Stats")
    st.bar_chart(df["Recommend"].value_counts())

if __name__ == "__main__":
    main()