# -*- coding: utf-8 -*-
"""FInal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Ins5XkYWyVbUmWc1pJnyieujCBtuD4R
"""

#!pip install streamlit pyngrok openpyxl -q

!ngrok config add-authtoken 2yVDomBX9OB1HYmt1iwcHx0Sort_3XxcoDueTkTqWEc2KkGQc

import os
import subprocess
from pyngrok import ngrok

# Set Streamlit port
port = 8501

# Connect ngrok
ngrok.set_auth_token("2yVDomBX9OB1HYmt1iwcHx0Sort_3XxcoDueTkTqWEc2KkGQc")  # Replace with your ngrok auth token
public_url = ngrok.connect(port)

# Launch Streamlit
print(f"Streamlit app running at: {public_url}")
!streamlit run app.py --server.port {port}

